<!doctype html>
<html lang="en">
<head>
    <?php require_once VIEW.'shared/meta.shared.phtml'?>
    <link rel="stylesheet" href="../../../public/css/style.css">
    <script defer src="../../../public/js/category-select.js"></script>
    <script defer src="../../../../public/js/active-route.js"></script>
    <title> Vaje 2 SP</title>
</head>
<body>
<?php require_once VIEW.'shared/header.shared.phtml'?>
<?php if (isset($this->viewData['error'])) : ?>
    <div class="alert alert-danger"><?= $this->error ?></div>
<?php endif; ?>

<div class="alert alert-danger" id="validation-error" style="display: none"></div>
<main class="signup-form">
    <form method="post">
        <div class="form-group">
            <label for="username"><b>Change your username</b></label>
            <input required type="text" class="form-control" id="username" name="username" placeholder="Enter username..." value=" <?= $this->user->getUsername()?>"/>
        </div>
        <div class="form-group">
            <label for="email"><b>Change your email</b></label>
            <input required type="email" class="form-control" id="email" name="email" placeholder="Enter email..." value=" <?= $this->user->getEmail()?>" />
        </div>
        <div class="form-group">
            <label for="firstName"><b>Change your first name</b></label>
            <input required type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter first name..." value=" <?= $this->user->getFirstName()?>" />
        </div>
        <div class="form-group">
            <label for="lastName"><b>Change your last name</b></label>
            <input required type="text" class="form-control" id="lastName" name="lastName" placeholder="Enter last name..." value=" <?= $this->user->getLastName()?>"/>
        </div>
        <div class="form-group">
            <label for="telephone"><b>Change your telephone number</b></label>
            <input required type="tel" class="form-control" id="telephone" name="telephone" placeholder="Enter telephone number..." value=" <?= $this->user->getTelephone()?>" />
        </div>
        <div class="form-group">
            <label for="address"><b>Change your address</b></label>
            <input required type="text" class="form-control" id="address" name="address" placeholder="Enter your address..." value=" <?= $this->user->getAddress()?>" />
        </div>
        <div class="form-group">
            <label for="post"><b>Change your post</b></label>
            <input required type="text" class="form-control" id="post" name="post" placeholder="Enter your post..." value=" <?= $this->user->getPost()?>" />
        </div>
        <input type="submit" name="submit" class="btn btn-primary" id="reg-submit" value="Update your information" />
    </form>
</main>
<?php require_once VIEW.'shared/footer.shared.phtml'?>
</body>
</html>
