<!doctype html>
<html lang="en">
<head>
    <?php require_once VIEW.'shared/meta.shared.phtml'?>
    <link rel="stylesheet" href="../../../public/css/style.css">
    <script defer src="../../../../public/js/active-route.js"></script>
    <title> Vaje 2 SP</title>
</head>
<body>
<?php require_once VIEW.'shared/header.shared.phtml'?>
<?php if (isset($this->viewData['error'])) : ?>
    <div class="alert alert-danger"><?= $this->error ?></div>
<?php endif; ?>
<main class="signup-form">
    <form method="post">
        <div class="form-group">
            <label for="username"><b>Username</b></label>
            <input required type="text" class="form-control" id="username" name="username" placeholder="Enter username or email..." />
        </div>
        <div class="form-group">
            <label for="password"><b>Password</b></label>
            <input required type="password" class="form-control" id="password" name="password" placeholder="Password ..." />
        </div>
        <input type="submit" name="submit" class="btn btn-primary" id="reg-submit" value="Login" />
    </form>
</main>
<?php require_once VIEW.'shared/footer.shared.phtml'?>
</body>
</html>