<header class="shadow">
    <script defer src="../../../../public/js/active-route.js"></script>
    <nav class="navbar navbar-expand-lg navbar-light main-navigation">
        <a href="/" class="navbar-brand ">
            <h1 class="display-4" id="app-title" >QuickAds</h1>
        </a>
        <div class="burger-button"  id="drawerButton">
            <span class="burger-line"></span>
            <span class="burger-line"></span>
            <span class="burger-line"></span>
        </div>
        <div class="drawer-container">
            <div class="drawer">
                <a class= "btn p-2 mr-1 rounded nav-btn" href="/" >Home</a>
                <?php if (AuthService::get()->isLoggedIn())  : ?>
                <a class="btn p-2 mr-1 rounded nav-btn" href="/ads/my-ads">My ads</a>
                <a class="btn p-2 mr-1 rounded nav-btn" href="/ads/publish">Publish an ad</a>
                <a class="btn p-2 mr-1 rounded nav-btn" href="/user/settings">Settings</a>
                <a class="btn p-2 mr-1 rounded nav-btn" href="/ads/delete-ad">Deleted ads</a>
                <a class="btn p-2 mr-1 rounded nav-btn" href="/auth/logout">Log out</a>
                <?php if (AuthService::get()->getUser()->getIsAdmin())  : ?>
                <a class="btn p-2 mr-1 rounded nav-btn" href="/user/admin">Administration</a>
                    <?php endif; ?>
                <?php else : ?>
                <a class="btn p-2 mr-1 rounded nav-btn" href="/auth/login">Log in</a>
                <a class="btn p-2 mr-1 rounded nav-btn" href="/auth/register">Register</a>
                <?php endif; ?>

            </div>
        </div>
    </nav>
</header>